### ISSUE TITLE
The Modulelist forward in unet.py

### ISSUE THREAD

**Issue by daniel159357** [bot66/MNISTDiffusion#3]
Hello sir, I am playing aroung the unet.py for the modulelist function in Encoder and Decoder.

In your code, the forward is performed by a for-loop, which can be implemented successfully in my pc. When I change the forward hardcoded and I can still run the unet.py. However, running the train_mnist.py causes an error "IndexError: index 2 is out of range". 
Do you know the reason for that? Just curious to learn coding. Many Thanks.

### Hardcode:
    def forward(self,x,t=None):
        #Initiate
        x1 = self.init_conv(x)
        if t is not None:
            t=self.time_embedding(t)
        # Down
        x2, x_shortcut2 = self.encoder_blocks[0](x1, t)
        x3, x_shortcut3 = self.encoder_blocks[1](x2, t)
        x4, x_shortcut4 = self.encoder_blocks[2](x3, t)
        x5, x_shortcut5 = self.encoder_blocks[3](x4, t)

        # Mid
        x6 = self.mid_block(x5)

        # Up
        x7 = self.decoder_blocks[0](x6, x_shortcut5, t)
        x8 = self.decoder_blocks[1](x7, x_shortcut4, t)
        x9 = self.decoder_blocks[2](x8, x_shortcut3, t)
        x10 = self.decoder_blocks[3](x9, x_shortcut2, t)

        # final
        x = self.final_conv(x10)
        print("x:", x.shape)

        return x
![error](https://github.com/user-attachments/assets/af530578-bb40-4c85-b1a9-26fb868a247b)

**Comment by bot66** [comment]
You could use debug mode（F5） to trace all the values and further investigate.
